### ISSUE TITLE
Hi, I met 

### ISSUE THREAD

**Issue by gerham** [liufly/narrative-modeling#2]

**Comment by gerham** [comment]
where I can download the datasets with above data files?
data/train_event.json
data/val_event.json
data/test_event.json
data/train_sentiment.json
data/val_sentiment.json
data/test_sentiment.json
data/train_topic.json
data/val_topic.json
data/val_topic.json

I have download original ROCStories 2016 from https://www.cs.rochester.edu/nlp/rocstories/. But I don't know these files format and how to make them?

**Comment by liufly** [comment]
@gerham These are the processed train/val/test sets with words bearing aspect-triggering signals identified.
I'm not sure if I'm allowed to share these files on GitHub due to licensing concerns and have therefore chosen not to.
Please let me know your email and I'll send them to you.
